=== Khmelov/JD2017-12-16/src/by/it/sendetskaya/jd02_09/Shop.xsd
<?xml version ="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://by.it.sendetskaya.jd02_09"
        xmlns:tns="http://by.it.sendetskaya.jd02_09"
        elementFormDefault="qualified">
    <element name="Shop">
        <complexType>
            <sequence>
                <element name="Buyers"
                         type="tns:Buyers"
                         maxOccurs="unbounded">
                </element>
                <element name="Goods"
                         type="tns:Goods"
                         maxOccurs="unbounded">
                </element>
                <element name="Baskets"
                         type="tns:Baskets"
                         maxOccurs="unbounded">
                </element>
            </sequence>
        </complexType>
    </element>

        <complexType name="Buyers">
            <sequence>
                <element name="Buyer"
                         type="tns:Buyer"
                         maxOccurs="unbounded">
                </element>
            </sequence>
        </complexType>

    <complexType name="Buyer">
        <sequence>
            <element name="IdBuyer" type="positiveInteger"/>
            <element name="Email" type="string"/>
            <element name="Nickname" type="string"/>
            <element name="Password" type="string"/>
        </sequence>
    </complexType>

        <complexType name="Goods">
            <sequence>
                <element name="Good"
                         type="tns:Good"
                         maxOccurs="unbounded">
                </element>
            </sequence>
        </complexType>

    <complexType name="Good">
        <all>
            <element name="IdGood" type="positiveInteger"/>
            <element name="Name" type="string"/>
            <element name="Price" type="double"/>
            <element name="Size" type="string"/>
            <element name="Colour" type="string"/>
            <element name="Structure" type="string"/>
            <element name="Description" type="string"/>
        </all>
    </complexType>

    <complexType name="Baskets">
        <sequence>
            <element name="Basket"
                     type="tns:Basket"
                     maxOccurs="unbounded">
            </element>
        </sequence>
    </complexType>

    <complexType name="Basket">
        <sequence>
            <element name="IdBuyerInBasket" type="positiveInteger"/>
            <element name="IdGoodInBasket" type="positiveInteger"/>
            <element name="Quantity" type="positiveInteger"/>
            <element name="Sum" type="double"/>
        </sequence>
    </complexType>


</schema>

=== Khmelov/JD2017-12-16/src/by/it/sendetskaya/jd02_09/Shop+XSD.xml
<?xml version ="1.0" encoding="UTF-8"?>
<Shop xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://by.it.sendetskaya.jd02_09 Shop.xsd"
         xmlns="http://by.it.sendetskaya.jd02_09">
        <Buyers>
            <Buyer>
                <IdBuyer>1</IdBuyer>
                <Email>qweqwe@ya.ru</Email>
                <Nickname>IvanA1234</Nickname>
                <Password>qwerty</Password>
            </Buyer>
            <Buyer>
                <IdBuyer>2</IdBuyer>
                <Email>qwe@ya.ru</Email>
                <Nickname>Ivan1234</Nickname>
                <Password>qwery</Password>
            </Buyer>
        </Buyers>
        <Goods>
            <Good>
                <IdGood>1</IdGood>
                <Name>Кофта</Name>
                <Price>12.0</Price>
                <Size>s</Size>
                <Colour>Зеленый</Colour>
                <Structure>Хлопок</Structure>
                <Description>
                    Крутая новая кофта
                </Description>
            </Good>
            <Good>
                <IdGood>2</IdGood>
                <Name>Штаны</Name>
                <Price>10.50</Price>
                <Size>s</Size>
                <Colour>Красный</Colour>
                <Structure>Вельвет</Structure>
                <Description>
                    Крутые новые штаны
                </Description>
            </Good>
        </Goods>
        <Baskets>
            <Basket>
                <IdBuyerInBasket>2</IdBuyerInBasket>
                <IdGoodInBasket>2</IdGoodInBasket>
                <Quantity>1</Quantity>
                <Sum>10.50</Sum>
            </Basket>
            <Basket>
                <IdBuyerInBasket>1</IdBuyerInBasket>
                <IdGoodInBasket>1</IdGoodInBasket>
                <Quantity>2</Quantity>
                <Sum>24.0</Sum>
            </Basket>
        </Baskets>
    </Shop>
