=== Khmelov/JD2017-12-16/src/by/it/kozlov/jd02_07/Persons.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="myNamespace"
        xmlns:tns="myNamespace"
        elementFormDefault="qualified">
    <element name="Persons">
        <complexType>
            <sequence>
                <element name="Person"
                         type="tns:Person"
                         maxOccurs="unbounded">
                </element>
            </sequence>
        </complexType>
    </element>
    <complexType name="Person">
        <sequence>
            <element name="Email" type="string"/>
            <element name="Password" type="string"/>
            <element name="Address" type="string"/>
            <element name="PhoneNumber" type="integer"/>
            <element name="Brand" type="tns:Brand"/>
        </sequence>
        <attribute name="nickName" type="ID"/>
    </complexType>
    <complexType name="Brand">
        <sequence>
            <element name="Title" type="string"/>
            <element name="Model" type="tns:Model"
                     minOccurs="0"
                     maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    <complexType name="Model">
        <sequence>
            <element name="Name" type="string"/>
            <element name="Class" type="string"/>
            <element name="Price" type="integer"/>
            <element name="Years" type="integer"/>
        </sequence>
    </complexType>
</schema>

=== Khmelov/JD2017-12-16/src/by/it/kozlov/jd02_07/Persons XSD.xml
<?xml version="1.0" encoding="UTF-8"?>
<Persons xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="myNamespace Persons.xsd"
         xmlns="myNamespace">
    <Person nickName="bayernkraft.by">
        <Email>bmw.service@bayernkraft.by</Email>
        <Password>bayernkraft</Password>
        <Address>г. Минск, ул. Панченко, 9</Address>
        <PhoneNumber>+375447730077</PhoneNumber>
        <Brand>
            <Title>BMW</Title>
            <Model>
                <Name>7 series</Name>
                <Class>Седан</Class>
                <Price>164400</Price>
                <Years>2018</Years>
            </Model>
            <Model>
                <Name>X6</Name>
                <Class>Кроссовер</Class>
                <Price>132000</Price>
                <Years>2018</Years>
            </Model>
        </Brand>
    </Person>

    <Person nickName="mercedes-benz.by">
        <Email>info@mercedes-benz.by</Email>
        <Password>mercedes</Password>
        <Address>г. Минск, ул. Тимирязева, 70</Address>
        <PhoneNumber>+375296039999</PhoneNumber>
        <Brand>
            <Title>Mercedes-Benz</Title>
            <Model>
                <Name>E 200 4MATIC</Name>
                <Class>Седан</Class>
                <Price>137706</Price>
                <Years>2018</Years>
            </Model>
            <Model>
                <Name>GLS</Name>
                <Class>Внедорожник</Class>
                <Price>164700</Price>
                <Years>2018</Years>
            </Model>
        </Brand>
    </Person>
</Persons>
